# Generated by Django 3.2.7 on 2022-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(),
        ),
    ]
