# Generated by Django 3.2.7 on 2022-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_songreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='songreview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
