# Generated by Django 3.2.7 on 2022-02-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
